# Generated by Django 5.2.5 on 2025-09-01 07:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0003_rename_contact_person_clinic_contact_person_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clinic",
            old_name="sonsent_template",
            new_name="consent_template",
        ),
    ]
