# Generated by Django 4.2.23 on 2025-08-25 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0003_rename_contact_person_clinic_contact_person_name_and_more"),
        ("therapy", "0009_alter_therapistprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parentprofile",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clinic.clinic",
            ),
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clinic.clinic",
            ),
        ),
    ]
