# Generated by Django 5.1.4 on 2025-08-26 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0010_parentprofile_clinic_therapistprofile_clinic"),
    ]

    operations = [
        migrations.RunSQL(
            # Drop the old foreign key constraint
            "ALTER TABLE therapy_child DROP FOREIGN KEY therapy_child_parent_id_ad6843c4_fk_users_user_id;",
            # Reverse SQL (add it back if needed)
            "ALTER TABLE therapy_child ADD CONSTRAINT therapy_child_parent_id_ad6843c4_fk_users_user_id FOREIGN KEY (parent_id) REFERENCES users_user(id);"
        ),
        migrations.RunSQL(
            # Add the correct foreign key constraint
            "ALTER TABLE therapy_child ADD CONSTRAINT therapy_child_parent_id_fk_therapy_parentprofile FOREIGN KEY (parent_id) REFERENCES therapy_parentprofile(id);",
            # Reverse SQL (drop it if needed)
            "ALTER TABLE therapy_child DROP FOREIGN KEY therapy_child_parent_id_fk_therapy_parentprofile;"
        ),
    ]
